# Generated by Django 5.2.8 on 2025-12-02 10:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('Street', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=10)),
                ('Contact_No', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Course', models.CharField(max_length=100)),
                ('Room_No', models.CharField(max_length=10)),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monthly_Price', models.FloatField(default=5000.0)),
            ],
        ),
        migrations.CreateModel(
            name='Today_Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(unique=True)),
                ('Breakfast', models.CharField(max_length=300)),
                ('Lunch', models.CharField(max_length=300)),
                ('Dinner', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('Complaint_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Complaint_Text', models.TextField()),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.CharField(default='Pending', max_length=20)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messmate_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('Subscription_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Plan_Name', models.CharField(max_length=50)),
                ('Monthly_Price', models.FloatField()),
                ('Requested_On', models.DateField(default=django.utils.timezone.localdate)),
                ('Start_Date', models.DateField(blank=True, null=True)),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Rejected', 'Rejected'), ('Cancellation Pending', 'Cancellation Pending'), ('Cancellation Rejected', 'Cancellation Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messmate_app.student')),
            ],
        ),
    ]
